version: '3'
services:
  mongodb:
    container_name: Athena-mongo-db
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=athenadb
      - MONGO_INITDB_ROOT_PASSWORD=a7hena!
      - MONGO_INITDB_DATABASE=root-db
    ports:
      - '27017:27017'
    volumes:
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo/db-mongo-athena:/data/db